/**
 * Crop & Tree identification data.
 *
 * To add a crop: append an object to the `crops` array with the same shape.
 * Questions are auto-generated from this data in the crop section module.
 *
 * Extra targeted comparison questions go in `extraCropQuestions`.
 * Each needs: q, correct, wrong (array of 3), imageName, explanation.
 */

export const crops = [
  { name: 'Almond',     category: 'Tree nut',              leaf: 'Narrow, lance-shaped, finely serrated edges, 3\u20135 inches long',                             bark: 'Gray-brown, rough and fissured on mature trees',                                  distinguish: 'Longer, narrower leaves than peach; hull splits open at maturity unlike other stone fruits' },
  { name: 'Walnut',     category: 'Tree nut',              leaf: 'Compound pinnate with 5\u20139 large leaflets, aromatic when crushed',                           bark: 'Light gray, deeply furrowed in diamond patterns',                                  distinguish: 'Compound leaves set it apart from all stone fruits; strong scent when leaves are crushed' },
  { name: 'Pistachio',  category: 'Tree nut',              leaf: 'Compound with 3\u20135 rounded leaflets, leathery texture',                                     bark: 'Rough, grayish, with noticeable lenticels',                                       distinguish: 'Fewer, rounder leaflets than walnut; clusters of reddish-tan shells at maturity' },
  { name: 'Peach',      category: 'Stone fruit',            leaf: 'Lance-shaped, finely serrated, 3\u20136 inches, slightly curved',                               bark: 'Reddish-brown to gray, smooth when young, lightly fissured with age',              distinguish: 'Wider and more curved than almond leaf; no glands at leaf base unlike cherry' },
  { name: 'Nectarine',  category: 'Stone fruit',            leaf: 'Nearly identical to peach \u2014 lance-shaped, serrated, 3\u20136 inches',                       bark: 'Similar to peach \u2014 reddish-brown, smooth to lightly fissured',                distinguish: 'Fruit has smooth skin (no fuzz) unlike peach; leaves are virtually indistinguishable from peach' },
  { name: 'Plum',       category: 'Stone fruit',            leaf: 'Oval to oblong, finely serrated, 2\u20134 inches, smooth surface',                              bark: 'Dark brown to black, develops rough scaly plates',                                distinguish: 'Broader leaf shape than peach/almond; darker bark than cherry' },
  { name: 'Cherry',     category: 'Stone fruit',            leaf: 'Oval, doubly serrated, 2\u20135 inches, two small glands at the base of the blade',             bark: 'Distinctive shiny, reddish-brown with horizontal lenticels (lines)',               distinguish: 'Prominent glands at leaf base (peach lacks these); glossy bark with horizontal lines unlike plum' },
  { name: 'Pear',       category: 'Pome fruit',             leaf: 'Oval to round, glossy, finely serrated or smooth edges, thick and leathery',                    bark: 'Gray-brown, develops rectangular scaly blocks',                                   distinguish: 'Glossier, rounder leaf than apple; bark forms blockier pattern than apple' },
  { name: 'Apple',      category: 'Pome fruit',             leaf: 'Oval, serrated, soft downy underside, 2\u20134 inches',                                         bark: 'Gray-brown, irregularly scaly and flaky',                                         distinguish: 'Fuzzy leaf underside (pear is smooth/glossy); more irregular bark pattern than pear' },
  { name: 'Orange',     category: 'Citrus',                 leaf: 'Evergreen, oval, dark glossy green, winged petiole, aromatic oil glands',                        bark: 'Light brown, relatively smooth with shallow furrows',                              distinguish: 'Broader leaf than lemon; winged petiole wider than mandarin' },
  { name: 'Lemon',      category: 'Citrus',                 leaf: 'Evergreen, elliptical, lighter green than orange, strong citrus scent, minimal petiole wing',    bark: 'Light gray-brown, may have thorns on branches',                                   distinguish: 'Lighter green and more pointed leaf than orange; thorns more prominent than mandarin' },
  { name: 'Mandarin',   category: 'Citrus',                 leaf: 'Evergreen, small narrow lance-shaped, small winged petiole',                                     bark: 'Thin, smooth, light brown',                                                       distinguish: 'Smallest and narrowest leaf of common citrus; more compact tree form than orange' },
  { name: 'Grape',      category: 'Vine crop',              leaf: 'Large, palmately lobed (3\u20135 lobes), toothed margins, tendrils on vine',                     bark: 'Woody vine with shredding bark on older canes',                                   distinguish: 'Only crop on this list that is a vine; large lobed leaves are unmistakable' },
  { name: 'Tomato',     category: 'Vegetable (fruit crop)',  leaf: 'Compound, pinnate, strong pungent smell, hairy/sticky stems',                                   bark: 'N/A \u2014 herbaceous stem, green and hairy',                                     distinguish: 'Herbaceous annual, not a tree; distinctive tomato scent from leaves/stems' },
  { name: 'Strawberry', category: 'Small fruit',             leaf: 'Trifoliate (3 rounded, serrated leaflets), low-growing rosette',                                bark: 'N/A \u2014 herbaceous crown, runners along soil surface',                         distinguish: 'Ground-level trifoliate leaves; reproduces by runners along the ground' },
];

export const extraCropQuestions = [
  { q: 'Which stone fruit has prominent glands at the leaf base?',                                            correct: 'Cherry',                                                              wrong: ['Peach', 'Plum', 'Nectarine'],                                              imageName: 'Cherry',    explanation: 'Cherry leaves have two small glands at the blade base.' },
  { q: 'Which tree nut has compound pinnate leaves with 5\u20139 leaflets that are aromatic when crushed?',   correct: 'Walnut',                                                              wrong: ['Almond', 'Pistachio', 'Pecan'],                                            imageName: 'Walnut',    explanation: 'Walnut leaflets release a distinctive scent when crushed.' },
  { q: 'Which citrus has the narrowest, smallest leaves?',                                                    correct: 'Mandarin',                                                            wrong: ['Orange', 'Lemon', 'Grapefruit'],                                           imageName: 'Mandarin',  explanation: 'Mandarin has the most compact growth of common citrus.' },
  { q: 'Which crop reproduces by runners along the ground?',                                                  correct: 'Strawberry',                                                          wrong: ['Grape', 'Tomato', 'Blueberry'],                                            imageName: 'Strawberry', explanation: 'Strawberry sends out stolons (runners) to propagate.' },
  { q: 'Which tree has shiny, reddish-brown bark with horizontal lenticels?',                                 correct: 'Cherry',                                                              wrong: ['Peach', 'Plum', 'Almond'],                                                 imageName: 'Cherry',    explanation: 'Cherry bark\u2019s horizontal lines are a key field ID trait.' },
  { q: 'Which fruit tree\u2019s leaf has a fuzzy/downy underside?',                                           correct: 'Apple',                                                               wrong: ['Pear', 'Cherry', 'Plum'],                                                  imageName: 'Apple',     explanation: 'Apple leaves are pubescent underneath; pear leaves are glossy.' },
  { q: 'Peach and nectarine leaves are nearly identical. Main fruit difference?',                              correct: 'Nectarine has smooth skin; peach has fuzzy skin',                      wrong: ['Nectarine is larger', 'Peach is freestone; nectarine is cling', 'Nectarine is always yellow'], imageName: 'Nectarine', explanation: 'The only reliable difference is skin texture.' },
  { q: 'Which tree nut\u2019s bark forms deeply furrowed diamond-shaped patterns?',                           correct: 'Walnut',                                                              wrong: ['Almond', 'Pistachio', 'Pecan'],                                            imageName: 'Walnut',    explanation: 'Walnut bark has a distinctive diamond-furrowed pattern.' },
  { q: 'What distinguishes pear bark from apple bark?',                                                       correct: 'Pear bark forms rectangular scaly blocks; apple bark is irregularly flaky', wrong: ['Pear bark is smoother', 'Apple bark is darker', 'They are identical'],  imageName: 'Pear',      explanation: 'Pear bark is blockier; apple bark is more irregular.' },
  { q: 'Which of these is the only vine crop?',                                                               correct: 'Grape',                                                               wrong: ['Strawberry', 'Tomato', 'Kiwi'],                                            imageName: 'Grape',     explanation: 'Grape is a woody vine; others are herbaceous or low-growing.' },
  { q: 'Almond and peach leaves are both lance-shaped. How do you tell them apart?',                          correct: 'Almond leaves are narrower; peach leaves are wider and more curved',   wrong: ['Almond leaves are darker', 'Peach has fuzzy underside', 'Cannot distinguish'], imageName: 'Almond', explanation: 'Width and curvature are the key leaf differences.' },
  { q: 'Which crop is an herbaceous annual with compound pinnate leaves and a pungent smell?',                correct: 'Tomato',                                                              wrong: ['Strawberry', 'Grape', 'Walnut'],                                           imageName: 'Tomato',    explanation: 'Tomato stems/leaves have a distinctive pungent smell.' },
];
